"""changes in post table

Revision ID: 157e294cfc5d
Revises: d64cfc086757
Create Date: 2019-02-12 05:09:44.210863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157e294cfc5d'
down_revision = 'd64cfc086757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faminfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_father', sa.String(length=140), nullable=True),
    sa.Column('guardian_mother', sa.String(length=140), nullable=True),
    sa.Column('guardian_other', sa.String(length=140), nullable=True),
    sa.Column('telephone1', sa.Integer(), nullable=True),
    sa.Column('telephone2', sa.Integer(), nullable=True),
    sa.Column('nameofidpcamp', sa.String(length=140), nullable=True),
    sa.Column('yearsspentinidpcamp', sa.DateTime(), nullable=True),
    sa.Column('numberofsiblings', sa.Integer(), nullable=True),
    sa.Column('numberofsiblingswithnodding', sa.Integer(), nullable=True),
    sa.Column('numberofsiblingsalive', sa.Integer(), nullable=True),
    sa.Column('numberofsiblingswithepilepsy', sa.Integer(), nullable=True),
    sa.Column('noddingrelateddeathsinfam', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faminfo_nameofidpcamp'), 'faminfo', ['nameofidpcamp'], unique=False)
    op.create_index(op.f('ix_faminfo_noddingrelateddeathsinfam'), 'faminfo', ['noddingrelateddeathsinfam'], unique=False)
    op.create_index(op.f('ix_faminfo_numberofsiblings'), 'faminfo', ['numberofsiblings'], unique=False)
    op.create_index(op.f('ix_faminfo_numberofsiblingsalive'), 'faminfo', ['numberofsiblingsalive'], unique=False)
    op.create_index(op.f('ix_faminfo_numberofsiblingswithepilepsy'), 'faminfo', ['numberofsiblingswithepilepsy'], unique=False)
    op.create_index(op.f('ix_faminfo_numberofsiblingswithnodding'), 'faminfo', ['numberofsiblingswithnodding'], unique=False)
    op.create_index(op.f('ix_faminfo_yearsspentinidpcamp'), 'faminfo', ['yearsspentinidpcamp'], unique=False)
    op.add_column('post', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('muac', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'weight')
    op.drop_column('post', 'muac')
    op.drop_column('post', 'height')
    op.drop_column('post', 'bmi')
    op.drop_index(op.f('ix_faminfo_yearsspentinidpcamp'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_numberofsiblingswithnodding'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_numberofsiblingswithepilepsy'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_numberofsiblingsalive'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_numberofsiblings'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_noddingrelateddeathsinfam'), table_name='faminfo')
    op.drop_index(op.f('ix_faminfo_nameofidpcamp'), table_name='faminfo')
    op.drop_table('faminfo')
    # ### end Alembic commands ###
