"""Add default info in about_me column

Revision ID: 332cbc9b54f8
Revises: b46b11bffb89
Create Date: 2019-02-19 15:40:09.944248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332cbc9b54f8'
down_revision = 'b46b11bffb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_lat', table_name='user')
    op.drop_index('ix_user_lon', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_lon', 'user', ['lon'], unique=False)
    op.create_index('ix_user_lat', 'user', ['lat'], unique=False)
    # ### end Alembic commands ###
