"""Additional QuerySelectField table

Revision ID: 3e2019a79d91
Revises: c63c7cbfde40
Create Date: 2019-02-14 18:53:49.156076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2019a79d91'
down_revision = 'c63c7cbfde40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patientplaceofmedicalservicechoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patientplaceofmedicalservicechoice')
    # ### end Alembic commands ###
