"""CHANGES

Revision ID: 3ed3f9bc4954
Revises: 332cbc9b54f8
Create Date: 2019-02-25 14:53:59.070109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed3f9bc4954'
down_revision = '332cbc9b54f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=140), nullable=True),
    sa.Column('placelon', sa.String(length=64), nullable=True),
    sa.Column('placelat', sa.String(length=64), nullable=True),
    sa.Column('tolon', sa.String(length=64), nullable=True),
    sa.Column('tolat', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoint_timestamp'), 'waypoint', ['timestamp'], unique=False)
    op.drop_table('faminfo')
    op.add_column('user', sa.Column('ageofonset', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('dateofonset', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('guardian_father', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('guardian_mother', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('guardian_other', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('nameofidpcamp', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('noddingrelateddeathsinfam', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('numberofsiblings', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('numberofsiblingsalive', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('numberofsiblingswithepilepsy', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('numberofsiblingswithnodding', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('telephone1', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('telephone2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('veryfirstsignssymptoms', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('watersourceduringonset', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('where', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('yearsspentinidpcamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_ageofonset'), 'user', ['ageofonset'], unique=False)
    op.create_index(op.f('ix_user_dateofonset'), 'user', ['dateofonset'], unique=False)
    op.create_index(op.f('ix_user_nameofidpcamp'), 'user', ['nameofidpcamp'], unique=False)
    op.create_index(op.f('ix_user_noddingrelateddeathsinfam'), 'user', ['noddingrelateddeathsinfam'], unique=False)
    op.create_index(op.f('ix_user_numberofsiblings'), 'user', ['numberofsiblings'], unique=False)
    op.create_index(op.f('ix_user_numberofsiblingsalive'), 'user', ['numberofsiblingsalive'], unique=False)
    op.create_index(op.f('ix_user_numberofsiblingswithepilepsy'), 'user', ['numberofsiblingswithepilepsy'], unique=False)
    op.create_index(op.f('ix_user_numberofsiblingswithnodding'), 'user', ['numberofsiblingswithnodding'], unique=False)
    op.create_index(op.f('ix_user_veryfirstsignssymptoms'), 'user', ['veryfirstsignssymptoms'], unique=False)
    op.create_index(op.f('ix_user_watersourceduringonset'), 'user', ['watersourceduringonset'], unique=False)
    op.create_index(op.f('ix_user_where'), 'user', ['where'], unique=False)
    op.create_index(op.f('ix_user_yearsspentinidpcamp'), 'user', ['yearsspentinidpcamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_yearsspentinidpcamp'), table_name='user')
    op.drop_index(op.f('ix_user_where'), table_name='user')
    op.drop_index(op.f('ix_user_watersourceduringonset'), table_name='user')
    op.drop_index(op.f('ix_user_veryfirstsignssymptoms'), table_name='user')
    op.drop_index(op.f('ix_user_numberofsiblingswithnodding'), table_name='user')
    op.drop_index(op.f('ix_user_numberofsiblingswithepilepsy'), table_name='user')
    op.drop_index(op.f('ix_user_numberofsiblingsalive'), table_name='user')
    op.drop_index(op.f('ix_user_numberofsiblings'), table_name='user')
    op.drop_index(op.f('ix_user_noddingrelateddeathsinfam'), table_name='user')
    op.drop_index(op.f('ix_user_nameofidpcamp'), table_name='user')
    op.drop_index(op.f('ix_user_dateofonset'), table_name='user')
    op.drop_index(op.f('ix_user_ageofonset'), table_name='user')
    op.drop_column('user', 'yearsspentinidpcamp')
    op.drop_column('user', 'where')
    op.drop_column('user', 'watersourceduringonset')
    op.drop_column('user', 'veryfirstsignssymptoms')
    op.drop_column('user', 'telephone2')
    op.drop_column('user', 'telephone1')
    op.drop_column('user', 'numberofsiblingswithnodding')
    op.drop_column('user', 'numberofsiblingswithepilepsy')
    op.drop_column('user', 'numberofsiblingsalive')
    op.drop_column('user', 'numberofsiblings')
    op.drop_column('user', 'noddingrelateddeathsinfam')
    op.drop_column('user', 'nameofidpcamp')
    op.drop_column('user', 'guardian_other')
    op.drop_column('user', 'guardian_mother')
    op.drop_column('user', 'guardian_father')
    op.drop_column('user', 'dateofonset')
    op.drop_column('user', 'ageofonset')
    op.create_table('faminfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guardian_father', sa.VARCHAR(length=140), nullable=True),
    sa.Column('guardian_mother', sa.VARCHAR(length=140), nullable=True),
    sa.Column('guardian_other', sa.VARCHAR(length=140), nullable=True),
    sa.Column('telephone1', sa.INTEGER(), nullable=True),
    sa.Column('telephone2', sa.INTEGER(), nullable=True),
    sa.Column('nameofidpcamp', sa.VARCHAR(length=140), nullable=True),
    sa.Column('yearsspentinidpcamp', sa.DATETIME(), nullable=True),
    sa.Column('numberofsiblings', sa.INTEGER(), nullable=True),
    sa.Column('numberofsiblingswithnodding', sa.INTEGER(), nullable=True),
    sa.Column('numberofsiblingsalive', sa.INTEGER(), nullable=True),
    sa.Column('numberofsiblingswithepilepsy', sa.INTEGER(), nullable=True),
    sa.Column('noddingrelateddeathsinfam', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_waypoint_timestamp'), table_name='waypoint')
    op.drop_table('waypoint')
    # ### end Alembic commands ###
