"""Modifications On Case Definitions under User db.Modal

Revision ID: 7cee5c387024
Revises: fdab8e3623f3
Create Date: 2019-02-26 18:02:26.933869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cee5c387024'
down_revision = 'fdab8e3623f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('casedefinition_characteristics', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('casedefinition_name', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_user_casedefinition_characteristics'), 'user', ['casedefinition_characteristics'], unique=False)
    op.create_index(op.f('ix_user_casedefinition_name'), 'user', ['casedefinition_name'], unique=False)
    op.drop_index('ix_user_casedefinition', table_name='user')
    op.drop_column('user', 'casedefinition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('casedefinition', sa.VARCHAR(length=140), nullable=True))
    op.create_index('ix_user_casedefinition', 'user', ['casedefinition'], unique=False)
    op.drop_index(op.f('ix_user_casedefinition_name'), table_name='user')
    op.drop_index(op.f('ix_user_casedefinition_characteristics'), table_name='user')
    op.drop_column('user', 'casedefinition_name')
    op.drop_column('user', 'casedefinition_characteristics')
    # ### end Alembic commands ###
