"""user updates from greyapp maps etc

Revision ID: d64cfc086757
Revises: c81bac34faab
Create Date: 2019-01-31 11:25:01.247158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64cfc086757'
down_revision = 'c81bac34faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('color', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('parish', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('pob', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('subcounty', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('village', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_dob'), 'user', ['dob'], unique=False)
    op.create_index(op.f('ix_user_height'), 'user', ['height'], unique=False)
    op.create_index(op.f('ix_user_lat'), 'user', ['lat'], unique=False)
    op.create_index(op.f('ix_user_lon'), 'user', ['lon'], unique=False)
    op.create_index(op.f('ix_user_parish'), 'user', ['parish'], unique=False)
    op.create_index(op.f('ix_user_pob'), 'user', ['pob'], unique=False)
    op.create_index(op.f('ix_user_sex'), 'user', ['sex'], unique=False)
    op.create_index(op.f('ix_user_subcounty'), 'user', ['subcounty'], unique=False)
    op.create_index(op.f('ix_user_village'), 'user', ['village'], unique=False)
    op.create_index(op.f('ix_user_weight'), 'user', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_weight'), table_name='user')
    op.drop_index(op.f('ix_user_village'), table_name='user')
    op.drop_index(op.f('ix_user_subcounty'), table_name='user')
    op.drop_index(op.f('ix_user_sex'), table_name='user')
    op.drop_index(op.f('ix_user_pob'), table_name='user')
    op.drop_index(op.f('ix_user_parish'), table_name='user')
    op.drop_index(op.f('ix_user_lon'), table_name='user')
    op.drop_index(op.f('ix_user_lat'), table_name='user')
    op.drop_index(op.f('ix_user_height'), table_name='user')
    op.drop_index(op.f('ix_user_dob'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'village')
    op.drop_column('user', 'subcounty')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'pob')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'parish')
    op.drop_column('user', 'lon')
    op.drop_column('user', 'lat')
    op.drop_column('user', 'height')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'color')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
